title = "University of Stirling Computer Club"
baseURL = "https://stirlingcomputer.club"
languageCode = "en-gb"
theme = ["github.com/lower-elements/elemental"]

[module]

[[module.imports]]
path = "github.com/lower-elements/elemental"
disable=false
