title = "University of Stirling Computer Club"
baseURL = "https://stirlingcomputer.club"
languageCode = "en-gb"
theme = ["github.com/lower-elements/elemental"]

[params]
shortTitle = "USCC"

[params.author]
name = "USCC team"
email = "computerClubStirling@gmail.com"
url = "https://github.com/orgs/Stirling-USSC/people"

[menu]
  [[menu.social]]
  identifier = "instagram"
  name = "Instagram (ussc.io)"
  weight = -70
  url = "https://www.instagram.com/ussc.io/"
  [[menu.social]]
  identifier = "github"
  name = "Github (stirling-ussc)"
  weight = -50
  url = "https://github.com/stirling-ussc"
  [[menu.social]]
  identifier = "discord"
  name = "Discord (USSC server)"
  weight = -30
  url = "https://discord.gg/DZnAvAnhKD"

[module]
    [[module.imports]]
    path = "github.com/lower-elements/elemental"
    disable=false
